### ISSUE TITLE
This is simply shameless Literary inquisition。

### ISSUE THREAD

**Issue by maikebing** [nativesintech/endasfmascotry#50]
This is simply shameless Literary inquisition。

**Comment by ssb22** [comment]
The [literary inquisition](https://en.m.wikipedia.org/wiki/Literary_inquisition) involved people being punished by a government for using certain words.  As I understand it, Natives In Tech is not calling for the members of Apache Software Foundation to be punished by any government for their use of the word "Apache"; they just want the Foundation itself to voluntarily be more careful.  Or does 文字狱 have a less harsh meaning in modern Chinese that does not involve government persecution?  Could it be applied to the whole of trademark law?

**Comment by maikebing** [comment]
Any attempt by any organization or individual to persecute or restrict, or to recommend the prohibition of the use of commonly used and well-known words by moral or other means, I consider these acts to be literary inquisition

**Comment by ssb22** [comment]
Thanks.  I wonder if we can think of an alternative solution.

The Apache Software Foundation was named in 1999 (edit: and the Apache server itself was [named in 1995](https://lists.apache.org/thread/ccwgj56lovwl2n9rxqq7twqxf55dy1yc)).  At that time the world's search tools were not as good as they are now.  So it is understandable if ASF founders made a mistake: they thought the name Apache was only historical, and they didn't find out that 8 oppressed nations using the name Apache are still very much alive.  Simple mistake—blame the limitations of the research tools available to ASF at the time.

Now here we are 28 years later, and more Native Americans are getting interested in software development and in the world of Free software.  I'm sure the Free Software community would want them to feel welcome.  But instead of that, they are thinking "ouch, there's this thing called Apache that took its name from 8 of our oppressed nations".  **This is a bug** if it's not what the Free Software community wants people to feel when they start finding out about free software.

Asking ASF to change its name is one proposed solution.  There might be others.  ASF could for example write a better statement along the lines of "we really didn't mean to do that", explicitly acknowledge all 8 of the nations for whom the name "Apache" is special, and take other measures to make it right which might be more manageable than a complete name change (especially with millions of "downstream" projects maintained by volunteers that would all need to be updated—I mentioned this in #36).  Good software developers try to look beyond the actual request to the underlying need.  So instead of saying "no we can't rename Apache, go away", we can be more accommodating by saying "let's look at **why** you'd like us to rename Apache, what problem is that trying to solve, is there a better way to solve that problem" etc.  We are dealing with a legitimate and serious bug report—let's see what solutions the Free Software community can come up with.
